# -*- coding: utf-8 -*-
"""INFORME PRESUPUESTARIO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oi4xPJqhjmqfo1A8bDKYKgvgwVG5le_V
"""

# Instalar librerías necesarias (en Colab ya vienen pandas/openpyxl, pero por si acaso)
!pip install -q openpyxl xlsxwriter

import pandas as pd
import numpy as np
from google.colab import files
import io
import warnings
warnings.filterwarnings('ignore')

print("✅ Librerías listas")

def subir_archivo(mensaje):
    """Solicita archivo al usuario en Colab y retorna DataFrame"""
    print(f"⬆️ {mensaje}")
    uploaded = files.upload()
    nombre = list(uploaded.keys())[0]
    print(f"📄 Archivo recibido: {nombre}")
    # Detectar si es csv o excel
    if nombre.endswith('.csv'):
        return pd.read_csv(io.BytesIO(uploaded[nombre]), encoding='latin-1', low_memory=False)
    else:
        return pd.read_excel(io.BytesIO(uploaded[nombre]))

def escribir_titulo_y_df(writer, hoja, titulo, df, startrow=0, hidden_cols=None):
    """Escribe un título encima de los encabezados del DataFrame.
    hidden_cols: lista de nombres de columnas a ocultar en Excel."""
    df.to_excel(writer, sheet_name=hoja, startrow=startrow+1, index=False)
    ws = writer.sheets[hoja]
    ws.write(startrow, 0, titulo)
    # Ajustar ancho de columnas básico
    for i, col in enumerate(df.columns, 0):
        max_len = max(df[col].astype(str).map(len).max(), len(str(col))) + 2
        ws.set_column(i, i, min(max_len, 40))

    # Ocultar columnas especificadas
    if hidden_cols:
        # Create a format object for hidden columns
        hidden_format = writer.book.add_format({'hidden': True})
        for col in hidden_cols:
            if col in df.columns:
                col_idx = df.columns.get_loc(col)
                ws.set_column(col_idx, col_idx, None, hidden_format) # Use the format object here

def calcular_percentiles_serie(serie):
    """
    Calcula los percentiles de referencia y asigna a cada valor su percentil.
    Retorna: (tabla_resumen, serie_percentiles_asignados)
    """
    # Percentiles de referencia
    puntos = [1, 10, 25, 50, 75, 90, 99]
    vals = {p: np.percentile(serie.dropna(), p) for p in puntos}

    # Asignar percentil a cada observación
    def asignar_percentil(x):
        if pd.isna(x):
            return np.nan
        # Si supera el percentil 99, se denomina 100
        if x > vals[99]:
            return 100
        # Buscar el percentil más alto que no supera el valor
        asignado = 1
        for p in puntos:
            if x >= vals[p]:
                asignado = p
        return asignado

    perc_asignado = serie.apply(asignar_percentil)

    # Tabla resumen
    tabla = pd.DataFrame({
        'P': puntos,
        'Valor': [vals[p] for p in puntos]
    })
    return tabla, perc_asignado

def reordenar_columnas(df, es_filtrada=False):
    """
    Reordena las columnas del DataFrame.
    - PRINCIPAL: columnas prioritarias al inicio, resto conserva orden original.
    - TABLA FILTRADA: igual, pero columnas de variables (Var_Multiple_*)
      se ubican obligatoriamente DESPUÉS de 'Diff_Vig_Prev'.
    """
    prioritarias = ['Entidad', 'TIPO', 'DA', 'UE', 'FTE', 'Org.', 'Cat. Prg.',
                    'Descripción Cat. Prg.', 'Objeto', 'Descripcion Objeto Del Gasto']
    prioritarias = [c for c in prioritarias if c in df.columns]

    if es_filtrada:
        vars_cols = ['Var_Multiple_FTE', 'FTE_2', 'FTE_3',
                     'Var_Multiple_Org', 'Org_2', 'Org_3', 'Concat_Org']
        vars_cols = [c for c in vars_cols if c in df.columns]

        # Resto: ni prioritarias, ni vars, ni Diff_Vig_Prev
        resto = [c for c in df.columns if c not in prioritarias + vars_cols + ['Diff_Vig_Prev']]

        # Ubicar Diff_Vig_Prev después de Preventivo (o al final si no existe)
        if 'Preventivo' in resto:
            idx = resto.index('Preventivo') + 1
            resto.insert(idx, 'Diff_Vig_Prev')
        elif 'Presup. Vig.' in resto:
            idx = resto.index('Presup. Vig.') + 1
            resto.insert(idx, 'Diff_Vig_Prev')
        else:
            resto.append('Diff_Vig_Prev')

        return df[prioritarias + resto + vars_cols]
    else:
        resto = [c for c in df.columns if c not in prioritarias]
        return df[prioritarias + resto]

print("✅ Funciones auxiliares cargadas")

# ============================================
# 1. CARGAR INFORMES
# ============================================

# Informe (1) - Base
df_base = subir_archivo("Sube el INFORME (1) - archivo base")

# Informe (2) - Diccionario / Cat. Programáticas
df_dict = subir_archivo("Sube el INFORME (2) - Diccionario de datos (Cat. Prg.)")

print(f"\n🔹 Base: {df_base.shape}")
print(f"🔹 Diccionario: {df_dict.shape}")

# ============================================
# 2. MERGE 1:m - Cat. Prg. + Descripción
# ============================================

# Normalizar nombres de columnas (eliminar espacios extra)
df_base.columns = df_base.columns.str.strip()
df_dict.columns = df_dict.columns.str.strip()

# Asumiendo que en el diccionario hay: 'Cat. Prg.' y 'Descripción Cat. Prg.'
# Si tus columnas se llaman diferente, cámbialas aquí:
col_clave_base = 'Cat. Prg.'        # Ajusta si es necesario
col_clave_dict = 'Cat. Prg.'        # Ajusta si es necesario
col_desc_dict = 'Descripción Cat. Prg.'

# Verificar que existan
print("Columnas base:", df_base.columns.tolist())
print("Columnas dict:", df_dict.columns.tolist())

# Merge 1:m (left join)
df_principal = df_base.merge(
    df_dict[[col_clave_dict, col_desc_dict]],
    left_on=col_clave_base,
    right_on=col_clave_dict,
    how='left'
)

# Si quedó duplicada la clave del diccionario, eliminarla
if col_clave_dict in df_principal.columns and col_clave_dict != col_clave_base:
    df_principal.drop(columns=[col_clave_dict], inplace=True)

print(f"\n✅ PRINCIPAL creada: {df_principal.shape}")
df_principal.head(3)

# ============================================
# 2.1 AÑADIR COLUMNA TIPO (CORREGIDO)
# ============================================
def clasificar_tipo(valor):
    """Limpia espacios/tabs y clasifica por longitud exacta"""
    x = str(valor)
    n = len(x)
    if n == 11:
        return 'Actividad'
    elif n == 24:
        return 'Proyecto'
    else:
        return 'SN'

df_principal['TIPO'] = df_principal['Cat. Prg.'].apply(clasificar_tipo)
print("✅ Columna TIPO añadida a PRINCIPAL")

# ============================================
# 3. HOJA: INFORMES ORIGINALES (Tablas Dinámicas)
# ============================================

# Asegurar que columnas numéricas existan (ajusta nombres si difieren)
# Columnas esperadas:
# 'Presup. Vig.', 'Preventivo', 'Mod. Aprobadas', 'Org', 'FTE', 'DA', 'UE', 'Objeto'

# Diccionarios de descripción para lookups rápidos (se usan en todos los informes)
desc_cat_map = df_principal.drop_duplicates('Cat. Prg.').set_index('Cat. Prg.')['Descripción Cat. Prg.'] if 'Descripción Cat. Prg.' in df_principal.columns else pd.Series()
desc_obj_map = df_principal.drop_duplicates('Objeto').set_index('Objeto')['Descripcion Objeto Del Gasto'] if 'Descripcion Objeto Del Gasto' in df_principal.columns else pd.Series()

def crear_resumenes(df_orig):
    resultados = {}

    # -- a.1 Agregado --
    for agr in ['Org', 'FTE', 'DA', 'UE']:
        if agr in df_orig.columns:
            res = df_orig.groupby(agr).agg({
                'Presup. Vig.': 'sum',
                'Preventivo': 'sum'
            }).reset_index()
            # a.1 no lleva Cat. Prg. ni Objeto, por tanto no aplica descripción
            resultados[f'a.1_Suma_by_{agr}'] = res

    # -- a.2 Desagregado por Cat. Prg. --
    if 'Cat. Prg.' in df_orig.columns and 'FTE' in df_orig.columns:
        res = df_orig.groupby(['Cat. Prg.', 'FTE']).agg({
            'Presup. Vig.': 'sum',
            'Preventivo': 'sum'
        }).reset_index()
        # Renombrar para que quede como Cat prog | FTE | Pres
        # INDICAR QUE 'Pres' SE TRATA DE Preventivo
        res.rename(columns={'Preventivo': 'Pres'}, inplace=True)
        # Añadir descripción de categoría programática
        if not desc_cat_map.empty:
            res['Descripción Cat. Prg.'] = res['Cat. Prg.'].map(desc_cat_map)
            res = res[['Cat. Prg.', 'Descripción Cat. Prg.', 'FTE', 'Pres']]
        else:
            res = res[['Cat. Prg.', 'FTE', 'Pres']]
        resultados['a.2_CatPrg_FTE'] = res

    # -- a.3 Desagregado por Objeto --
    for agr in ['Org', 'FTE', 'DA', 'UE']:
        if agr in df_orig.columns and 'Objeto' in df_orig.columns:
            res = df_orig.groupby(['Objeto', agr]).agg({
                'Mod. Aprobadas': 'sum'
            }).reset_index()
            # Añadir descripción del objeto
            if not desc_obj_map.empty:
                res['Descripcion Objeto Del Gasto'] = res['Objeto'].map(desc_obj_map)
                res = res[['Objeto', 'Descripcion Objeto Del Gasto', agr, 'Mod. Aprobadas']]
            resultados[f'a.3_Objeto_by_{agr}'] = res

    # -- a.4 Desagregado por Objeto > 0 --
    if 'Objeto' in df_orig.columns and 'Mod. Aprobadas' in df_orig.columns:
        df_pos = df_orig[df_orig['Mod. Aprobadas'] > 0].copy()
        if not df_pos.empty and 'FTE' in df_pos.columns:
            # Agregado por Objeto-FTE
            res = df_pos.groupby(['Objeto', 'FTE']).agg({
                'Mod. Aprobadas': 'sum'
            }).reset_index()
            # Calcular percentiles sobre la suma agregada
            tabla_perc, res['P'] = calcular_percentiles_serie(res['Mod. Aprobadas'])
            # Añadir descripción del objeto
            if not desc_obj_map.empty:
                res['Descripcion Objeto Del Gasto'] = res['Objeto'].map(desc_obj_map)
                res = res[['Objeto', 'Descripcion Objeto Del Gasto', 'FTE', 'Mod. Aprobadas', 'P']]
            else:
                res = res[['Objeto', 'FTE', 'Mod. Aprobadas', 'P']]
            resultados['a.4_Objeto_FTE_POSITIVAS'] = res
            resultados['a.4_Percentiles_Referencia'] = tabla_perc

    # -- a.5 Desagregado por Objeto < 0 --
    if 'Objeto' in df_orig.columns and 'Mod. Aprobadas' in df_orig.columns:
        df_neg = df_orig[df_orig['Mod. Aprobadas'] < 0].copy()
        if not df_neg.empty and 'FTE' in df_neg.columns:
            res = df_neg.groupby(['Objeto', 'FTE']).agg({
                'Mod. Aprobadas': 'sum'
            }).reset_index()
            tabla_perc, res['P'] = calcular_percentiles_serie(res['Mod. Aprobadas'])
            # Añadir descripción del objeto
            if not desc_obj_map.empty:
                res['Descripcion Objeto Del Gasto'] = res['Objeto'].map(desc_obj_map)
                res = res[['Objeto', 'Descripcion Objeto Del Gasto', 'FTE', 'Mod. Aprobadas', 'P']]
            else:
                res = res[['Objeto', 'FTE', 'Mod. Aprobadas', 'P']]
            resultados['a.5_Objeto_FTE_NEGATIVAS'] = res
            resultados['a.5_Percentiles_Referencia'] = tabla_perc

    return resultados

resumenes = crear_resumenes(df_principal)
print(f"✅ Resúmenes generados: {list(resumenes.keys())}")

# ============================================
# 4. HOJA: TABLA FILTRADA
# ============================================

df_filtrada = df_principal.copy()

# --- Crear variables de identificación ---
# Variable: más de una FTE por Cat. Prg.
fte_por_cat = df_filtrada.groupby('Cat. Prg.')['FTE'].nunique()
df_filtrada['Var_Multiple_FTE'] = df_filtrada['Cat. Prg.'].map(lambda x: 1 if fte_por_cat.get(x, 0) > 1 else 0)

# FTE 2 y FTE 3 (las adicionales ordenadas)
ftes_por_cat = df_filtrada.groupby('Cat. Prg.')['FTE'].unique().apply(lambda x: sorted(set(x)))
def obtener_fte_n(cat, n):
    ftes = ftes_por_cat.get(cat, [])
    return ftes[n] if len(ftes) > n else None

df_filtrada['FTE_2'] = df_filtrada['Cat. Prg.'].apply(lambda x: obtener_fte_n(x, 1))
df_filtrada['FTE_3'] = df_filtrada['Cat. Prg.'].apply(lambda x: obtener_fte_n(x, 2))

# Variable: más de una Org por Cat. Prg.
org_por_cat = df_filtrada.groupby('Cat. Prg.')['Org.'].nunique()
df_filtrada['Var_Multiple_Org'] = df_filtrada['Cat. Prg.'].map(lambda x: 1 if org_por_cat.get(x, 0) > 1 else 0)

# Org 2 y Org 3
orgs_por_cat = df_filtrada.groupby('Cat. Prg.')['Org.'].unique().apply(lambda x: sorted(set(x)))
def obtener_org_n(cat, n):
    orgs = orgs_por_cat.get(cat, [])
    return orgs[n] if len(orgs) > n else None

df_filtrada['Org_2'] = df_filtrada['Cat. Prg.'].apply(lambda x: obtener_org_n(x, 1))
df_filtrada['Org_3'] = df_filtrada['Cat. Prg.'].apply(lambda x: obtener_org_n(x, 2))

# Concatenar Org;Org2;Org3
df_filtrada['Concat_Org'] = df_filtrada.apply(
    lambda r: ';'.join([str(v) for v in [r['Org.'], r['Org_2'], r['Org_3']] if pd.notna(v)]), axis=1
)

# --- FILTROS (aplicados secuencialmente con AND) ---
print(f"Inicio TABLA FILTRADA: {df_filtrada.shape[0]} filas")

# 1. Eliminar si contiene 119; 314; 411 en la concatenación
mask = ~df_filtrada['Concat_Org'].astype(str).str.contains('119|314|411', na=False, regex=True)
df_filtrada = df_filtrada[mask]
print(f"Filtro Org (119,314,411): {df_filtrada.shape[0]} filas")

# 2. Eliminar "gastos recurrentes"
recurrentes_keywords = ['MANTENIMIENTO', 'FUNCIONAMIENTO']
if 'Descripción Cat. Prg.' in df_filtrada.columns:
    patron = '|'.join(recurrentes_keywords)
    mask = ~df_filtrada['Descripción Cat. Prg.'].str.contains(patron, case=False, na=False, regex=True)
    df_filtrada = df_filtrada[mask]
    print(f"Filtro recurrentes: {df_filtrada.shape[0]} filas")

# 3. Eliminar "SALUD"
if 'Descripción Cat. Prg.' in df_filtrada.columns:
    mask = ~df_filtrada['Descripción Cat. Prg.'].str.contains('Salud', case=False, na=False)
    df_filtrada = df_filtrada[mask]
    print(f"Filtro Salud: {df_filtrada.shape[0]} filas")

# 4. Eliminar Leyes
leyes_keywords = ['NIÑO', 'NIÑEZ', 'VIOLENCIA', 'ZOONOSIS', 'SEDES', 'VIH',
                  'CONTROL', 'TRATA', 'FELCV', 'CAMBIO CL', 'DRAGADO',
                  'DESASTRE', 'DISCAPACIDAD', 'Dignidad', 'ADULTO']
if 'Descripción Cat. Prg.' in df_filtrada.columns:
    patron = '|'.join(leyes_keywords)
    mask = ~df_filtrada['Descripción Cat. Prg.'].str.contains(patron, case=False, na=False, regex=True)
    df_filtrada = df_filtrada[mask]
    print(f"Filtro Leyes: {df_filtrada.shape[0]} filas")

# 5. MANTENER si Diferencia Vig-Prev by (Cat. Prg.) > 0
df_filtrada['Diff_Vig_Prev'] = df_filtrada['Presup. Vig.'] - df_filtrada['Preventivo']
diff_cat = df_filtrada.groupby('Cat. Prg.')['Diff_Vig_Prev'].sum()
cats_pos = diff_cat[diff_cat > 0].index.tolist()
df_filtrada = df_filtrada[df_filtrada['Cat. Prg.'].isin(cats_pos)]
print(f"Filtro Diff Cat>0 (mantener): {df_filtrada.shape[0]} filas")

# 6. MANTENER partidas individuales con Diferencia Vig-Prev > 0
df_filtrada = df_filtrada[df_filtrada['Diff_Vig_Prev'] > 0]
print(f"Filtro Diff individual >0 (mantener): {df_filtrada.shape[0]} filas")

# 7. OPCIONAL: Eliminar si Diferencia Vig-Prev by (Objeto) < 1000
# Descomenta las siguientes líneas si deseas activarlo
# diff_obj2 = df_filtrada.groupby('Objeto')['Diff_Vig_Prev'].sum()
# objs_peq = diff_obj2[diff_obj2 < 1000].index.tolist()
# df_filtrada = df_filtrada[~df_filtrada['Objeto'].isin(objs_peq)]
# print(f"Filtro Diff Objeto<<1000 (opcional): {df_filtrada.shape[0]} filas")

print(f"\n✅ TABLA FILTRADA final: {df_filtrada.shape}")

# ============================================
# 4.1 AÑADIR COLUMNA TIPO A TABLA FILTRADA (CORREGIDO)
# ============================================
df_filtrada['TIPO'] = df_filtrada['Cat. Prg.'].apply(clasificar_tipo)
print("✅ Columna TIPO añadida a TABLA FILTRADA")

# ============================================
# 5. CLASIFICACIÓN - Percentiles
# ============================================

# --- INF.F.1: Percentiles by Cat. Prg. ---
diff_cat_filtrada = df_filtrada.groupby('Cat. Prg.')['Diff_Vig_Prev'].sum().reset_index()
tabla_perc_1, diff_cat_filtrada['P'] = calcular_percentiles_serie(diff_cat_filtrada['Diff_Vig_Prev'])

# Añadir Descripción Cat. Prg.
if not desc_cat_map.empty:
    diff_cat_filtrada['Descripción Cat. Prg.'] = diff_cat_filtrada['Cat. Prg.'].map(desc_cat_map)
    diff_cat_filtrada = diff_cat_filtrada[['Cat. Prg.', 'Descripción Cat. Prg.', 'Diff_Vig_Prev', 'P']]
else:
    diff_cat_filtrada = diff_cat_filtrada[['Cat. Prg.', 'Diff_Vig_Prev', 'P']]

# Renombrar para claridad
diff_cat_filtrada.rename(columns={'Diff_Vig_Prev': 'Diferencia_Vig_Prev'}, inplace=True)

# --- INF.F.2: Percentiles by Objeto ---
diff_obj_filtrada = df_filtrada.groupby('Objeto')['Diff_Vig_Prev'].sum().reset_index()
tabla_perc_2, diff_obj_filtrada['P'] = calcular_percentiles_serie(diff_obj_filtrada['Diff_Vig_Prev'])

# Añadir descripciones (usamos la primera ocurrencia por Objeto)
if not desc_obj_map.empty:
    diff_obj_filtrada['Descripcion Objeto Del Gasto'] = diff_obj_filtrada['Objeto'].map(desc_obj_map)
if not desc_cat_map.empty:
    # Tomamos la Descripción Cat. Prg. más frecuente/first para ese Objeto
    desc_cat_por_obj = df_filtrada.groupby('Objeto')['Descripción Cat. Prg.'].first()
    diff_obj_filtrada['Descripción Cat. Prg.'] = diff_obj_filtrada['Objeto'].map(desc_cat_por_obj)
# Agregar Cat. Prg. al inicio (primera ocurrencia por Objeto)
cat_prg_por_obj = df_filtrada.groupby('Objeto')['Cat. Prg.'].first()
diff_obj_filtrada['Cat. Prg.'] = diff_obj_filtrada['Objeto'].map(cat_prg_por_obj)


# Renombrar
diff_obj_filtrada.rename(columns={'Diff_Vig_Prev': 'Diferencia_Vig_Prev'}, inplace=True)

# ORDENAR COLUMNAS EXACTAMENTE COMO SE SOLICITÓ:
# Cat. Prg. | Descripción (Cat. Prg.) | Objeto | Descripcion Objeto Del Gasto | Diferencia_Vig_Prev | P
cols_inf_f2 = []
if 'Cat. Prg.' in diff_obj_filtrada.columns:
    cols_inf_f2.append('Cat. Prg.')
if 'Descripción Cat. Prg.' in diff_obj_filtrada.columns:
    cols_inf_f2.append('Descripción Cat. Prg.')
cols_inf_f2.append('Objeto')
if 'Descripcion Objeto Del Gasto' in diff_obj_filtrada.columns:
    cols_inf_f2.append('Descripcion Objeto Del Gasto')
cols_inf_f2.extend(['Diferencia_Vig_Prev', 'P'])
diff_obj_filtrada = diff_obj_filtrada[cols_inf_f2]

print("✅ Percentiles calculados")
print(f"INF.F.1: {diff_cat_filtrada.shape}")
print(f"INF.F.2: {diff_obj_filtrada.shape}")

# ============================================
# 6. EXPORTAR EXCEL MULTI-HOJA
# ============================================

nombre_salida = 'Informe_Procesado.xlsx'

# Reordenar columnas de PRINCIPAL antes de escribir
df_principal = reordenar_columnas(df_principal)

# Reordenar columnas de TABLA FILTRADA antes de escribir
df_filtrada = reordenar_columnas(df_filtrada, es_filtrada=True)

with pd.ExcelWriter(nombre_salida, engine='xlsxwriter') as writer:

    # --- HOJA: PRINCIPAL ---
    escribir_titulo_y_df(writer, 'PRINCIPAL', 'DATOS PRINCIPALES (Merge Base + Diccionario)', df_principal)

    # --- HOJA: INFORMES ORIGINALES ---
    hoja_io = 'INFORMES ORIGINALES'
    fila_actual = 0
    for nombre_tabla, df_tabla in resumenes.items():
        if not df_tabla.empty:
            titulo = nombre_tabla.replace('_', ' ').upper()
            df_tabla.to_excel(writer, sheet_name=hoja_io, startrow=fila_actual+1, index=False)
            ws = writer.sheets[hoja_io]
            ws.write(fila_actual, 0, titulo)
            fila_actual += len(df_tabla) + 3  # Espacio entre tablas

    # --- HOJA: TABLA FILTRADA ---
    cols_ocultas_filtrada = ['Var_Multiple_FTE', 'FTE_2', 'FTE_3',
                             'Var_Multiple_Org', 'Org_2', 'Org_3', 'Concat_Org']
    escribir_titulo_y_df(writer, 'TABLA FILTRADA', 'TABLA FILTRADA (Post-filtros)',
                         df_filtrada, hidden_cols=cols_ocultas_filtrada)

    # --- HOJA: INF.F.1 ---
    escribir_titulo_y_df(writer, 'INF.F.1', 'PERCENTILES BY CAT. PRG. (1-10-25-50-75-90-99)', diff_cat_filtrada)

    # --- HOJA: INF.F.2 ---
    escribir_titulo_y_df(writer, 'INF.F.2', 'PERCENTILES BY OBJETO (1-10-25-50-75-90-99)', diff_obj_filtrada)

    # ============================================
    # 6.1 HOJA: SALDOS (Resumen por TIPO y Cat. Prg.)
    # ============================================
    df_saldos = df_filtrada.groupby(['TIPO', 'Cat. Prg.', 'Descripción Cat. Prg.'], as_index=False).agg({
        'Presup. Vig.': 'sum',
        'Preventivo': 'sum',
        'Diff_Vig_Prev': 'sum'
    })
    df_saldos.rename(columns={'Diff_Vig_Prev': 'Diferencia Vig-Prev'}, inplace=True)
    # Reordenar columnas exactamente como solicitado
    cols_saldos = ['TIPO', 'Cat. Prg.', 'Descripción Cat. Prg.', 'Presup. Vig.', 'Preventivo', 'Diferencia Vig-Prev']
    df_saldos = df_saldos[cols_saldos]
    df_saldos = df_saldos.sort_values(['TIPO', 'Diferencia Vig-Prev'], ascending=[True, False])
    escribir_titulo_y_df(writer, 'SALDOS CAT', 'SALDOS POR TIPO Y CAT. PRG. (RESUMEN)', df_saldos)

    # ============================================
    # 6.2 HOJA: SALDOS 2 (Detalle por TIPO, Cat. Prg. y Objeto)
    # ============================================
    df_saldos2 = df_filtrada.groupby(['TIPO', 'Cat. Prg.', 'Descripción Cat. Prg.',
                                      'Objeto', 'Descripcion Objeto Del Gasto'], as_index=False).agg({
        'Presup. Vig.': 'sum',
        'Preventivo': 'sum',
        'Diff_Vig_Prev': 'sum'
    })
    df_saldos2.rename(columns={'Diff_Vig_Prev': 'Diferencia Vig-Prev'}, inplace=True)
    cols_saldos2 = ['TIPO', 'Cat. Prg.', 'Descripción Cat. Prg.', 'Objeto',
                    'Descripcion Objeto Del Gasto', 'Presup. Vig.', 'Preventivo', 'Diferencia Vig-Prev']
    df_saldos2 = df_saldos2[cols_saldos2]
    df_saldos2 = df_saldos2.sort_values(['TIPO', 'Cat. Prg.', 'Diferencia Vig-Prev'],
                                          ascending=[True, True, False])
    escribir_titulo_y_df(writer, 'SALDOS Obj', 'SALDOS POR TIPO, CAT. PRG. Y OBJETO (DETALLE)', df_saldos2)

print(f"✅ Archivo '{nombre_salida}' generado con éxito")

# ============================================
# 7. DESCARGAR
# ============================================
files.download(nombre_salida)
print("⬇️ Descarga iniciada...")