# -*- coding: utf-8 -*-
"""limpieza inf. presupuestos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pqNDsGKzbf15x1CN9Dxcoi8XW_CvjkNM
"""

# ============================================================
# PROCESAMIENTO DE REPORTE DINÁMICO - GOOGLE COLAB
# ============================================================

# 0. SUBIR EL ARCHIVO
# Ejecuta esta celda y usa el botón "Elegir archivos" para subir tu archivo
from google.colab import files
uploaded = files.upload()

# Obtener el nombre del archivo subido
import os
file_name = list(uploaded.keys())[0]
print(f"Archivo subido: {file_name}")

# ============================================================
# 1. IMPORTAR LIBRERÍAS Y CARGAR DATOS
# ============================================================
import pandas as pd
import numpy as np

# Leer el archivo Excel (sin encabezado para manejar la estructura)
df = pd.read_excel(file_name, header=None)

print(f"Dimensiones originales: {df.shape}")
print(f"Primeras filas:\n{df.head(3)}")

# ============================================================
# 2. ELIMINAR ENCABEZADOS REPETIDOS (mantener solo el primero)
# ============================================================

# Eliminar la primera columna vacía (índice 0)
df = df.drop(columns=[0])

# Establecer la fila 1 como encabezado principal
df.columns = df.iloc[1]
df = df.drop(index=1).reset_index(drop=True)

# Eliminar TODAS las filas donde 'Entidad' == 'Entidad' (encabezados repetidos)
# y también eliminar filas vacías iniciales
df = df[df['Entidad'] != 'Entidad'].reset_index(drop=True)
df = df.dropna(subset=['Entidad']).reset_index(drop=True)

print(f"\nDimensiones después de limpiar encabezados repetidos: {df.shape}")

# ============================================================
# 3. CREAR TABLA DE DATOS (convertir tipos numéricos)
# ============================================================

# Lista de columnas numéricas
numeric_cols = [
    'Presupuesto Inicial', 'Mod. Aprobadas', 'Presup. Vig.',
    'Preventivo', 'Compromiso', 'Devengado', 'Pagado',
    'Saldo Por Pagar', 'Porcen. ', 'Saldo Deveng.'
]

# Convertir a numérico (coerce convierte errores a NaN)
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

print("\nTipos de datos después de conversión:")
print(df.dtypes)

# ============================================================
# 4. AÑADIR NUEVA COLUMNA: Diferencia Vig-Prev
# ============================================================

df['Diferencia Vig-Prev'] = df['Presup. Vig.'] - df['Preventivo']

print(f"\n✅ Nueva columna 'Diferencia Vig-Prev' agregada.")
print(f"   Fórmula: Presup. Vig. - Preventivo")
print(f"\nPrimeros 5 valores de la nueva columna:")
print(df[['Presup. Vig.', 'Preventivo', 'Diferencia Vig-Prev']].head())

# ============================================================
# 5. DESCARGAR EL DOCUMENTO PROCESADO
# ============================================================

output_file = 'REgaReporteDinamico_Procesado.xlsx'
df.to_excel(output_file, index=False, engine='openpyxl')

print(f"\n📁 Archivo procesado guardado como: {output_file}")

# Descargar automáticamente
files.download(output_file)

print("\n" + "="*60)
print("RESUMEN DEL PROCESAMIENTO:")
print("="*60)
print(f"• Filas de datos: {len(df)}")
print(f"• Columnas totales: {len(df.columns)}")
print(f"• Columnas: {', '.join(df.columns.tolist())}")
print(f"• Encabezados repetidos eliminados: ✅")
print(f"• Nueva columna 'Diferencia Vig-Prev': ✅")
print("="*60)

# ============================================================
# 6. APERTURA PARA SIGUIENTES ACCIONES
# ============================================================
# El DataFrame 'df' queda disponible en memoria para